"""A minimal mock SGLang chat-completions backend for the session-server bench.

Unlike `miles.utils.test_utils.mock_sglang_server.MockSGLangServer` (which
loads a tokenizer and re-encodes every turn), this backend does NO tokenization:
it serves PRE-BUILT synthetic response bodies generated by
`bench_session_server_overhead` (the same `TurnSpec.response_body` bytes the
CPU micro-benchmark validates against). That keeps the backend's own CPU cost
trivial so the measured wall time / latency reflects the SESSION SERVER's
`json.loads` / validate / record work, not the mock's.

Turn mapping is stateless: turn `k` of a session carries `2*k + 1` chat
`messages` (k prior user/assistant pairs + the new user turn), so the backend
recovers `turn_index = (len(messages) - 1) // 2` from the request body alone —
no per-session state, no session_id needed (the router rewrites the path to a
bare `v1/chat/completions` anyway).

Run as a subprocess target (`run_mock_r3_backend`) so it owns its own GIL,
exactly like a real upstream router/engine would, and so the session server's
RSS is measured without the backend's payload bytes folded in.
"""

from __future__ import annotations

import asyncio
import json
import socket

import setproctitle
import uvicorn
from fastapi import FastAPI, Request
from starlette.responses import Response


def build_mock_app(response_bodies: list[bytes], inference_interval: float = 0.0) -> FastAPI:
    """A FastAPI app that returns `response_bodies[turn_index]` per chat.

    `response_bodies` is the per-turn list of fully-serialized chat-completion
    response bytes (with the large `routed_experts` R3 blob already embedded).

    `inference_interval` (seconds) simulates the model's generation time: the
    handler `await`s that long before responding. It is a non-blocking sleep,
    so many concurrent chats stay in-flight together exactly like a real engine
    serving overlapping requests — which is precisely what lets a worker overlap
    distinct sessions' upstream waits (AC-5). At the default 0 the backend
    responds immediately (the continuous back-to-back stress case).
    """
    app = FastAPI()
    n_turns = len(response_bodies)

    @app.get("/health")
    async def health() -> Response:
        return Response(content=b'{"status":"ok"}', media_type="application/json")

    @app.post("/v1/chat/completions")
    async def chat(request: Request) -> Response:
        payload = json.loads(await request.body())
        messages = payload.get("messages", [])
        # turn k carries 2*k + 1 messages; clamp to the last spec defensively.
        turn_index = min((len(messages) - 1) // 2, n_turns - 1)
        if inference_interval > 0:
            await asyncio.sleep(inference_interval)
        return Response(content=response_bodies[turn_index], media_type="application/json")

    # The bench drives only chat; a catch-all keeps a stray proxy from 404-ing.
    @app.api_route("/{path:path}", methods=["GET", "POST", "PUT", "DELETE", "PATCH"])
    async def catch_all(path: str) -> Response:
        return Response(content=b'{"status":"ok"}', media_type="application/json")

    return app


def run_mock_r3_backend(response_bodies: list[bytes], host: str, port: int, inference_interval: float = 0.0) -> None:
    """`multiprocessing.Process` target: serve the mock backend on host:port.

    `inference_interval` (seconds) is the simulated per-chat generation delay
    (see `build_mock_app`).

    `timeout_keep_alive` is raised well above uvicorn's 5s default: the OLD
    single-process session server blocks its one event loop for tens-to-hundreds
    of ms per huge-body `json.loads` under the GIL, so with many concurrent
    sessions an upstream keep-alive connection can sit idle for seconds between
    a worker's turns. At the 5s default the backend would reap that idle
    connection and the next httpx reuse fails with a `ReadError` (the proxy
    surfaces it as a 502) — a benchmark-harness artifact, not the behavior under
    test. A large keep-alive window removes that artifact for BOTH OLD and NEW.
    """
    setproctitle.setproctitle("miles-bench-mock-r3-backend")
    app = build_mock_app(response_bodies, inference_interval=inference_interval)
    # Bind our own SO_REUSEPORT socket so N backend processes can share one
    # host:port and the kernel balances connections across them. Safe because
    # the turn mapping above is stateless — any request may hit any shard. This
    # is what keeps the mock off the measurement's critical path: a single
    # process saturates one core streaming large-R3 bodies to 16 workers.
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEPORT, 1)
    sock.bind((host, port))
    config = uvicorn.Config(app, log_level="warning", timeout_keep_alive=600)
    asyncio.run(uvicorn.Server(config).serve(sockets=[sock]))
